// The 56-day backbone. Every lesson file is written from this table: titles, grammar points,
// target words (already stress-marked), the speaking scenario and the media topics.
// Kinds follow the course week: days 1-5 lessons, day 6 immersion, day 7 review (and so on).

import type { DayKind, SyllabusDay, Tri } from "./types.ts";

const kindOf = (n: number): DayKind => (n % 7 === 6 ? "immersion" : n % 7 === 0 ? "review" : "lesson");

type Row = [n: number, title: Tri, grammar: string[], words: string[], scenario: string, topics: string[]];

const rows: Row[] = [
  // ── Week 1 · Sounds and first words ──────────────────────────────────────────
  [1, { ru: "Алфави́т 1: знако́мые бу́квы", en: "Alphabet 1: familiar letters", ar: "الأبجدية ١: الحروف المألوفة" },
    ["The 33-letter alphabet; 5 'true friends' that look and sound as in English: А К М О Т", "7 'false friends' that look English but sound different: В Е Н Р С У Х", "Reading syllables and first words; Russian has no articles (дом = a house / the house)"],
    ["ма́ма", "кот", "кто", "так", "там", "нет", "вот", "сок", "торт", "метро́", "рестора́н", "теа́тр", "Москва́", "у́тро"],
    "Reading aloud: the tutor shows short words built only from today's 12 letters and you read them, then say what they mean.",
    ["alphabet", "pronunciation"]],
  [2, { ru: "Алфави́т 2: но́вые фо́рмы", en: "Alphabet 2: new shapes", ar: "الأبجدية ٢: أشكال جديدة" },
    ["13 new letters: Б Г Д З И Й Л П Ф Э Ю Я Ё", "Vowel pairs: hard а э ы о у and soft я е и ё ю", "Э́то… = this is…: Russian drops 'is/are' in the present"],
    ["да", "э́то", "па́па", "приве́т", "пока́", "где", "вода́", "фо́то", "парк", "банк", "суп", "я́блоко", "зонт", "лифт", "ёлка"],
    "Point and name: the tutor asks Э́то парк? and you answer Да, э́то парк. or Нет, э́то банк.",
    ["alphabet", "pronunciation", "greetings"]],
  [3, { ru: "Алфави́т 3: шипя́щие и зна́ки", en: "Alphabet 3: hushing sounds and signs", ar: "الأبجدية ٣: أصوات الشين والعلامات" },
    ["The last letters: Ж Ш Щ Ч Ц Ы and the soft sign Ь / hard sign Ъ", "Stress and vowel reduction: unstressed о sounds like а (молоко́ → malakO)", "Final devoicing: хлеб sounds like 'khlep'"],
    ["здра́вствуйте", "до свида́ния", "спаси́бо", "пожа́луйста", "извини́те", "хорошо́", "чай", "молоко́", "хлеб", "сыр", "маши́на", "здесь", "день", "ночь"],
    "Polite basics in a shop: greet formally, ask for tea and bread with please, say thank you, apologise and say goodbye.",
    ["alphabet", "stress", "pronunciation", "greetings", "handwriting"]],
  [4, { ru: "Знако́мство", en: "Introductions", ar: "التعارف" },
    ["Меня́ зову́т… / Как тебя́ (вас) зову́т?", "Personal pronouns я ты он она́ мы вы они́", "ты or вы: informal, formal and plural 'you'"],
    ["я", "ты", "он", "она́", "мы", "вы", "они́", "как", "Меня́ зову́т…", "Как тебя́ зову́т?", "Как вас зову́т?", "О́чень прия́тно.", "И мне то́же.", "то́же", "а", "и", "Отку́да вы?", "Я из Еги́пта."],
    "A welcome party for international students: introduce yourself to a student (ты) and to a professor (вы).",
    ["introductions", "greetings", "questions"]],
  [5, { ru: "Как дела́? Чи́сла от 0 до 10", en: "How are you? Numbers 0–10", ar: "كيف الحال؟ الأعداد من ٠ إلى ١٠" },
    ["Как дела́? — Хорошо́ / норма́льно / пло́хо / отли́чно; А у тебя́?", "Numbers 0–10 and phone numbers digit by digit", "Yes/no questions use rising intonation only; Где? — здесь / там"],
    ["ноль", "оди́н", "два", "три", "четы́ре", "пять", "шесть", "семь", "во́семь", "де́вять", "де́сять", "Как дела́?", "отли́чно", "норма́льно", "пло́хо", "А у тебя́?"],
    "Small talk with a classmate: how are you, then swap phone numbers and read them back digit by digit.",
    ["numbers", "greetings", "questions"]],
  [6, { ru: "Пе́сни и мультфи́льмы", en: "Songs and cartoons", ar: "أغانٍ ورسوم متحركة" },
    ["Listening for words you know; reading printed and handwritten letters"],
    ["бу́ква", "звук", "сло́во", "пе́сня", "мультфи́льм", "медве́дь", "де́вочка"],
    "Tell the tutor which words you recognised in the song and the cartoon.",
    ["alphabet", "songs", "cartoon", "handwriting"]],
  [7, { ru: "Повторе́ние: неде́ля 1", en: "Review: week 1", ar: "مراجعة: الأسبوع ١" },
    ["Review: the alphabet, stress, greetings, introductions, numbers 0–10"],
    [],
    "Speaking test: greet the examiner, introduce yourself, say where you are from and read a phone number aloud.",
    ["alphabet", "greetings", "introductions", "numbers"]],

  // ── Week 2 · Me and my world ─────────────────────────────────────────────────
  [8, { ru: "Он, она́, оно́: род", en: "He, she, it: gender", ar: "المذكر والمؤنث والمحايد" },
    ["Three genders by ending: consonant or -й → он; -а / -я → она́; -о / -е → оно́", "Nouns in -ь: learn the gender (день — он, ночь — она́)", "мой / моя́ / моё and твой / твоя́ / твоё"],
    ["стол", "стул", "кни́га", "окно́", "ко́мната", "дверь", "телефо́н", "компью́тер", "су́мка", "ключ", "письмо́", "мо́ре", "мой", "твой"],
    "Show the tutor around your room on a video call: Э́то мой стол. Э́то моя́ ко́мната.",
    ["gender", "possessives"]],
  [9, { ru: "Мно́жественное число́", en: "Plurals", ar: "الجمع" },
    ["Plural endings -ы / -и (masculine, feminine) and -а / -я (neuter)", "The spelling rule: after г к х ж ш ч щ write и, never ы", "наш, ваш, его́, её, их"],
    ["наш", "ваш", "его́", "её", "их", "ру́чка", "каранда́ш", "тетра́дь", "слова́рь", "друг", "подру́га", "фотогра́фия", "го́род", "дом"],
    "Unpack a bag with the tutor: Э́то мои́ кни́ги? — Нет, э́то её кни́ги.",
    ["plurals", "possessives"]],
  [10, { ru: "Что ты де́лаешь?", en: "What are you doing? Verbs 1", ar: "ماذا تفعل؟ الأفعال (١)" },
    ["First conjugation: чита́ю, чита́ешь, чита́ет, чита́ем, чита́ете, чита́ют", "Question words: что, кто, где, как, почему́", "One present tense for 'I read' and 'I am reading'"],
    ["чита́ть", "знать", "рабо́тать", "де́лать", "понима́ть", "слу́шать", "отдыха́ть", "гуля́ть", "игра́ть", "ду́мать", "сейча́с", "всегда́", "ча́сто", "иногда́"],
    "Tell the tutor what you do at different times: Сейча́с я чита́ю. Ве́чером я отдыха́ю.",
    ["present-tense", "questions"]],
  [11, { ru: "Я говорю́ по-ру́сски", en: "I speak Russian: verbs 2", ar: "أتكلم الروسية: الأفعال (٢)" },
    ["Second conjugation: говорю́, говори́шь, говори́т, говори́м, говори́те, говоря́т", "Consonant change in the я-form: люби́ть → люблю́, ви́деть → ви́жу", "по-ру́сски, по-англи́йски, по-ара́бски with говори́ть and понима́ть"],
    ["говори́ть", "люби́ть", "смотре́ть", "звони́ть", "учи́ть", "по́мнить", "ви́деть", "язы́к", "по-ру́сски", "по-англи́йски", "по-ара́бски", "немно́го", "ме́дленно", "Повтори́те, пожа́луйста."],
    "A language exchange: say which languages you speak and how well, and ask the tutor to speak slowly and repeat.",
    ["present-tense", "languages"]],
  [12, { ru: "Моя́ семья́ и рабо́та", en: "My family and work", ar: "عائلتي وعملي" },
    ["У меня́ есть… = I have… (a fixed phrase for now)", "Professions need no article: Я инжене́р.", "Кто он? — Он врач. Кто она́? — Она́ учи́тель."],
    ["семья́", "оте́ц", "мать", "брат", "сестра́", "сын", "дочь", "муж", "жена́", "роди́тели", "врач", "инжене́р", "учи́тель", "студе́нт", "У меня́ есть…"],
    "Describe a family photo and ask about the tutor's family and job.",
    ["family", "professions"]],
  [13, { ru: "Смо́трим: семья́", en: "Watch: family", ar: "نشاهد: العائلة" },
    ["Listening for family words and professions in real speech"],
    ["де́душка", "ба́бушка", "внук", "вну́чка", "дя́дя", "тётя", "двою́родный брат"],
    "Retell who is who in the video, then describe your grandparents.",
    ["family", "cartoon", "listening"]],
  [14, { ru: "Повторе́ние: неде́ля 2", en: "Review: week 2", ar: "مراجعة: الأسبوع ٢" },
    ["Review: gender, plurals, possessives, both conjugations, family and professions"],
    [],
    "Speaking test: describe your family and what each person does, and say what you do every day.",
    ["gender", "plurals", "present-tense", "family"]],

  // ── Week 3 · Where? ──────────────────────────────────────────────────────────
  [15, { ru: "Где? Предло́жный паде́ж", en: "Where? The prepositional case", ar: "أين؟ حالة حرف الجر" },
    ["в / на + prepositional answer где?: в па́рке, на рабо́те", "Endings: -е for most nouns; -и for nouns in -ия and -ь (в Росси́и, в тетра́ди)", "до́ма = at home, with no preposition"],
    ["в", "на", "до́ма", "шко́ла", "университе́т", "магази́н", "о́фис", "у́лица", "пло́щадь", "страна́", "Росси́я", "Еги́пет", "Каи́р", "кварти́ра"],
    "Where are you right now, where is your family, where do you work or study?",
    ["prepositional", "city"]],
  [16, { ru: "В го́роде", en: "In the city", ar: "في المدينة" },
    ["Где нахо́дится…? — сле́ва, спра́ва, ря́дом, недалеко́, далеко́", "на for open places and events (на у́лице, на конце́рте), в for enclosed places", "Recognise irregular forms: в аэропорту́, в саду́, на мосту́"],
    ["апте́ка", "вокза́л", "музе́й", "кафе́", "больни́ца", "гости́ница", "остано́вка", "туале́т", "сле́ва", "спра́ва", "ря́дом", "далеко́", "недалеко́", "Где нахо́дится…?"],
    "Stop a passer-by (the tutor) and ask where the pharmacy, the metro and a hotel are.",
    ["city", "directions", "prepositional"]],
  [17, { ru: "Ско́лько сто́ит?", en: "How much is it? Numbers to 100", ar: "بكم هذا؟ الأعداد حتى ١٠٠" },
    ["11–19 with -на́дцать, tens 20–90 and compounds like два́дцать пять", "Ско́лько сто́ит…? with рубль / рубля́ / рубле́й learned as chunks", "Ско́лько? = how much / how many"],
    ["оди́ннадцать", "двена́дцать", "пятна́дцать", "два́дцать", "три́дцать", "со́рок", "пятьдеся́т", "сто", "ско́лько", "сто́ит", "рубль", "до́рого", "дёшево", "де́ньги"],
    "At a kiosk: ask the price of several things, understand the answers and say whether it is expensive or cheap.",
    ["numbers", "shopping"]],
  [18, { ru: "Кото́рый час?", en: "What time is it? Days of the week", ar: "كم الساعة؟ أيام الأسبوع" },
    ["Кото́рый час? / Ско́лько вре́мени? — час, два часа́, пять часо́в", "в + day: в понеде́льник, в сре́ду, в суббо́ту", "у́тром, днём, ве́чером, но́чью"],
    ["понеде́льник", "вто́рник", "среда́", "четве́рг", "пя́тница", "суббо́та", "воскресе́нье", "час", "мину́та", "у́тром", "днём", "ве́чером", "сего́дня", "за́втра"],
    "Plan the week with the tutor: agree on days and times for lessons and sport.",
    ["time", "days-week", "numbers"]],
  [19, { ru: "Где ты живёшь?", en: "Where do you live?", ar: "أين تسكن؟" },
    ["жить: живу́, живёшь, живёт, живём, живёте, живу́т", "о / об + prepositional: о Москве́, об А́нне", "Prepositional pronouns: обо мне, о тебе́, о нём, о ней"],
    ["жить", "а́дрес", "эта́ж", "райо́н", "центр", "писа́ть", "расска́зывать", "мечта́ть", "фильм", "но́вость", "о", "обо мне", "интере́сно", "сосе́д"],
    "Describe where you live — city, district, floor, neighbours — and talk about a film you like.",
    ["prepositional", "city"]],
  [20, { ru: "Смо́трим: у́лицы го́рода", en: "Watch: city streets", ar: "نشاهد: شوارع المدينة" },
    ["Listening to street interviews: catching places and numbers"],
    ["столи́ца", "проспе́кт", "па́мятник", "храм", "Кремль", "Кра́сная пло́щадь", "река́"],
    "Tell the tutor what you saw in the video and describe the centre of your own city.",
    ["city", "listening", "culture"]],
  [21, { ru: "Повторе́ние: неде́ля 3", en: "Review: week 3", ar: "مراجعة: الأسبوع ٣" },
    ["Review: prepositional case, places, numbers to 100, time and days"],
    [],
    "Speaking test: describe your neighbourhood, give prices and tell the examiner your weekly timetable.",
    ["prepositional", "numbers", "time"]],

  // ── Week 4 · Wants and needs ─────────────────────────────────────────────────
  [22, { ru: "Я хочу́ ко́фе: вини́тельный паде́ж", en: "I want a coffee: the accusative", ar: "أريد قهوة: حالة المفعول به" },
    ["The accusative answers что? for the direct object; masculine and neuter things do not change", "Feminine -а → -у, -я → -ю: Я чита́ю кни́гу. Я люблю́ му́зыку.", "хоте́ть: хочу́, хо́чешь, хо́чет, хоти́м, хоти́те, хотя́т"],
    ["хоте́ть", "покупа́ть", "брать", "му́зыка", "газе́та", "журна́л", "биле́т", "пода́рок", "ку́ртка", "пла́тье", "руба́шка", "ту́фли", "откры́тка", "ко́фе"],
    "Tell the tutor what you want to buy for each member of your family and why.",
    ["accusative", "shopping"]],
  [23, { ru: "Еда́ и напи́тки", en: "Food and drink", ar: "الطعام والمشروبات" },
    ["есть: ем, ешь, ест, еди́м, еди́те, едя́т", "пить: пью, пьёшь, пьёт, пьём, пьёте, пьют", "Accusative with food: Я ем ры́бу и пью во́ду."],
    ["есть", "пить", "мя́со", "ры́ба", "ку́рица", "сала́т", "рис", "карто́шка", "о́вощи", "фру́кты", "за́втрак", "обе́д", "у́жин", "вку́сно"],
    "Tell the tutor what you eat and drink for breakfast, lunch and dinner, and compare with Russian habits.",
    ["food", "accusative"]],
  [24, { ru: "В кафе́", en: "At the café", ar: "في المقهى" },
    ["мочь: могу́, мо́жешь, мо́жет, мо́жем, мо́жете, мо́гут", "Polite requests: Мо́жно…? / Да́йте, пожа́луйста… / Я бу́ду… (I'll have)", "Счёт, пожа́луйста."],
    ["мочь", "мо́жно", "меню́", "счёт", "официа́нт", "стака́н", "ча́шка", "таре́лка", "ло́жка", "ви́лка", "нож", "са́хар", "соль", "Я бу́ду…"],
    "Order a full meal in a Moscow café; the tutor is the waiter and one item is not available.",
    ["cafe", "food"]],
  [25, { ru: "Я тебя́ люблю́", en: "I love you: people in the accusative", ar: "أحبك: المفعول به للأشخاص" },
    ["Accusative pronouns: меня́, тебя́, его́, её, нас, вас, их", "Animate masculine nouns take -а / -я: Я зна́ю бра́та.", "Verbs with the accusative: люби́ть, знать, ви́деть, ждать, спра́шивать"],
    ["ждать", "спра́шивать", "встреча́ть", "приглаша́ть", "челове́к", "лю́ди", "мужчи́на", "же́нщина", "ребёнок", "де́ти", "де́вушка", "па́рень", "колле́га", "гость"],
    "Talk about who you know, love and are waiting for, then invite the tutor to a party.",
    ["accusative", "family", "invitations"]],
  [26, { ru: "Како́й? Прилага́тельные и цвета́", en: "Which one? Adjectives and colours", ar: "أيّ؟ الصفات والألوان" },
    ["Adjectives agree: но́вый дом / но́вая кни́га / но́вое окно́ / но́вые кни́ги", "Stressed -ой (большо́й) and the spelling rule (хоро́ший, ру́сский)", "Како́й? Кака́я? Како́е? Каки́е?"],
    ["но́вый", "ста́рый", "большо́й", "ма́ленький", "хоро́ший", "плохо́й", "краси́вый", "дорого́й", "дешёвый", "кра́сный", "си́ний", "бе́лый", "чёрный", "зелёный", "како́й"],
    "Shop for clothes: describe colours and sizes and compare two items; the tutor is the shop assistant.",
    ["adjectives", "colors", "shopping"]],
  [27, { ru: "Смо́трим: ры́нок", en: "Watch: the market", ar: "نشاهد: السوق" },
    ["Listening for food, prices and polite requests at a market"],
    ["ры́нок", "покупа́тель", "ка́сса", "ски́дка", "сда́ча", "о́чередь", "све́жий"],
    "Retell what the people in the video bought, then role-play buying fruit at a market.",
    ["shopping", "food", "listening"]],
  [28, { ru: "Контро́льная то́чка A1", en: "A1 checkpoint", ar: "نقطة التقييم A1" },
    ["Review of weeks 1–4: alphabet to accusative, food, café, shopping, adjectives"],
    [],
    "A1 speaking test: introduce yourself, order in a café, buy clothes and describe your home.",
    ["accusative", "food", "cafe", "adjectives"]],

  // ── Week 5 · My day ──────────────────────────────────────────────────────────
  [29, { ru: "Вчера́: проше́дшее вре́мя", en: "Yesterday: the past tense", ar: "أمس: الزمن الماضي" },
    ["Past tense: stem + -л / -ла / -ло / -ли (чита́л, чита́ла, чита́ли)", "быть in the past: был, была́, бы́ло, бы́ли", "Time words: вчера́, позавчера́, ра́ньше, давно́, на про́шлой неде́ле"],
    ["быть", "вчера́", "позавчера́", "ра́ньше", "давно́", "неда́вно", "пото́м", "неде́ля", "ме́сяц", "год", "про́шлый", "о́тпуск", "кани́кулы", "пра́здник"],
    "Tell the tutor what you did yesterday and last weekend; the tutor asks follow-up questions.",
    ["past-tense"]],
  [30, { ru: "Мой день: глаго́лы на -ся", en: "My day: reflexive verbs", ar: "يومي: الأفعال الانعكاسية" },
    ["-ся / -сь verbs: я просыпа́юсь, ты просыпа́ешься", "Sequencing a routine: снача́ла, пото́м, по́сле э́того", "Clock times as chunks: в семь часо́в, в полови́не восьмо́го"],
    ["просыпа́ться", "встава́ть", "умыва́ться", "одева́ться", "занима́ться", "возвраща́ться", "ложи́ться спать", "начина́ться", "зака́нчиваться", "обы́чно", "ра́но", "по́здно", "снача́ла", "душ"],
    "Describe your typical weekday from waking up to going to bed; compare it with the tutor's.",
    ["daily-routine", "reflexive-verbs"]],
  [31, { ru: "У меня́ нет вре́мени", en: "I have no time: the genitive 1", ar: "ليس عندي وقت: حالة الإضافة (١)" },
    ["Genitive singular: -а / -я (masculine, neuter), -ы / -и (feminine)", "нет + genitive: нет вре́мени, нет маши́ны", "у + genitive for 'have': у бра́та, у меня́, у него́, у неё"],
    ["вре́мя", "соба́ка", "ко́шка", "да́ча", "вопро́с", "пробле́ма", "иде́я", "па́спорт", "кошелёк", "телеви́зор", "холоди́льник", "вещь", "к сожале́нию", "ничего́"],
    "Say what you and your family have and don't have, and give polite excuses: У меня́ нет вре́мени.",
    ["genitive"]],
  [32, { ru: "Мно́го и ма́ло", en: "A lot and a little: the genitive 2", ar: "كثير وقليل: حالة الإضافة (٢)" },
    ["мно́го / ма́ло / ско́лько / не́сколько + genitive", "Numbers: 1 + nominative; 2–4 + genitive singular; 5–20 + genitive plural", "Possession (маши́на бра́та) and из / от / до / по́сле + genitive"],
    ["мно́го", "ма́ло", "не́сколько", "килогра́мм", "литр", "буты́лка", "паке́т", "кусо́к", "па́чка", "шту́ка", "из", "от", "до", "по́сле"],
    "Make a shopping list for a family dinner with quantities and packages, then buy it from the tutor.",
    ["genitive", "shopping", "food"]],
  [33, { ru: "Сде́лал и́ли де́лал?", en: "Did or was doing? Verb aspect", ar: "فعلتُ أم كنتُ أفعل؟ الفعل التام وغير التام" },
    ["Imperfective = process, habit, repetition; perfective = one completed result", "Pairs: де́лать — сде́лать, чита́ть — прочита́ть, писа́ть — написа́ть, покупа́ть — купи́ть, говори́ть — сказа́ть", "Signals: ча́сто, всегда́, ка́ждый день → imperfective; уже́, наконе́ц → usually perfective"],
    ["сде́лать", "прочита́ть", "написа́ть", "купи́ть", "сказа́ть", "посмотре́ть", "позвони́ть", "пригото́вить", "гото́вить", "уже́", "ещё", "наконе́ц", "ка́ждый день", "успе́ть"],
    "Tell the tutor what you were doing this week and what you managed to finish.",
    ["aspect", "past-tense"]],
  [34, { ru: "Смо́трим: оди́н день в Москве́", en: "Watch: a day in Moscow", ar: "نشاهد: يوم في موسكو" },
    ["Listening to a real daily-routine vlog: past tense and time expressions"],
    ["буди́льник", "спеши́ть", "про́бка", "переры́в", "устава́ть", "выходно́й", "доро́га"],
    "Retell the vlogger's day in the past tense, then describe your own busiest day.",
    ["daily-routine", "listening", "culture"]],
  [35, { ru: "Повторе́ние: неде́ля 5", en: "Review: week 5", ar: "مراجعة: الأسبوع ٥" },
    ["Review: past tense, reflexive verbs, genitive, aspect"],
    [],
    "Speaking test: describe yesterday in detail, what you have and don't have, and what you finished this week.",
    ["past-tense", "genitive", "aspect"]],

  // ── Week 6 · Going places ────────────────────────────────────────────────────
  [36, { ru: "Мне нра́вится: да́тельный паде́ж", en: "I like it: the dative 1", ar: "يعجبني: حالة المستفيد (١)" },
    ["Dative pronouns: мне, тебе́, ему́, ей, нам, вам, им", "мне нра́вится / нра́вятся; мне ну́жно / мо́жно / нельзя́; мне хо́лодно, ску́чно", "Age: Мне два́дцать пять лет (год / го́да / лет)"],
    ["нра́виться", "ну́жно", "нельзя́", "хо́лодно", "тепло́", "ску́чно", "ве́село", "тру́дно", "легко́", "лет", "во́зраст", "спорт", "футбо́л", "кино́"],
    "Likes and dislikes: sport, films, food and cities; ask and say how old people in your family are.",
    ["dative"]],
  [37, { ru: "Позвони́ мне!", en: "Call me! The dative 2", ar: "اتصل بي! حالة المستفيد (٢)" },
    ["Noun dative: -у / -ю (masculine, neuter), -е (feminine): бра́ту, сестре́", "Verbs with the dative: дава́ть / дать, звони́ть, помога́ть, отвеча́ть, сове́товать, дари́ть", "к + dative for visiting a person: к врачу́, к дру́гу"],
    ["дава́ть", "дать", "помога́ть", "отвеча́ть", "сове́товать", "дари́ть", "пока́зывать", "объясня́ть", "обеща́ть", "сообще́ние", "к", "по телефо́ну", "день рожде́ния", "подари́ть"],
    "Plan birthday presents: who gives what to whom, and who you will call to invite.",
    ["dative", "phone-calls"]],
  [38, { ru: "За́втра: бу́дущее вре́мя", en: "Tomorrow: the future tense", ar: "غدًا: الزمن المستقبل" },
    ["Imperfective future: бу́ду, бу́дешь… + infinitive", "Perfective future: present-tense endings on a perfective verb (сде́лаю, прочита́ю)", "за́втра, послеза́втра, че́рез неде́лю, в сле́дующем году́"],
    ["послеза́втра", "ско́ро", "че́рез", "сле́дующий", "план", "бу́дущее", "наде́яться", "собира́ться", "обяза́тельно", "мо́жет быть", "путеше́ствовать", "выходны́е", "начина́ть", "зако́нчить"],
    "Talk about your plans for the weekend, next month and next year.",
    ["future-tense", "aspect"]],
  [39, { ru: "Иду́ и е́ду: глаго́лы движе́ния", en: "Going on foot and by transport: verbs of motion", ar: "أذهب ماشيًا وراكبًا: أفعال الحركة" },
    ["идти́ (one direction, now) vs ходи́ть (regularly, there and back)", "е́хать vs е́здить for travel by transport; на авто́бусе, на метро́, пешко́м", "Куда́? в / на + accusative (в шко́лу) vs Где? в / на + prepositional (в шко́ле)"],
    ["идти́", "ходи́ть", "е́хать", "е́здить", "куда́", "туда́", "сюда́", "домо́й", "пешко́м", "авто́бус", "трамва́й", "такси́", "по́езд", "самолёт"],
    "Where are you going now and how do you usually get to work, to the shops and to see friends?",
    ["motion-verbs", "transport"]],
  [40, { ru: "Как дое́хать?", en: "How do I get there? Directions", ar: "كيف أصل؟ الاتجاهات" },
    ["Как пройти́ / дое́хать до + genitive…?", "Directions: пря́мо, напра́во, нале́во, до перекрёстка", "Imperatives for directions: иди́те, поверни́те, сади́тесь, выходи́те"],
    ["пря́мо", "напра́во", "нале́во", "поверну́ть", "перекрёсток", "светофо́р", "переса́дка", "ста́нция", "вы́ход", "вход", "ка́рта", "у́гол", "пройти́", "дое́хать"],
    "The tutor is a tourist lost in Cairo, then you are lost in Moscow: ask for and give directions.",
    ["directions", "transport", "imperative"]],
  [41, { ru: "Смо́трим: моско́вское метро́", en: "Watch: the Moscow metro", ar: "نشاهد: مترو موسكو" },
    ["Listening to metro announcements and a guided tour"],
    ["ваго́н", "эскала́тор", "ли́ния", "осторо́жно", "Две́ри закрыва́ются.", "Сле́дующая ста́нция…", "пассажи́р"],
    "Plan a metro route between two stations with one change and explain it to the tutor.",
    ["transport", "culture", "listening"]],
  [42, { ru: "Повторе́ние: неде́ля 6", en: "Review: week 6", ar: "مراجعة: الأسبوع ٦" },
    ["Review: dative, future tense, verbs of motion, directions"],
    [],
    "Speaking test: say what you like and need, give directions from your home to a café and describe next week's plans.",
    ["dative", "future-tense", "motion-verbs"]],

  // ── Week 7 · People and preferences ──────────────────────────────────────────
  [43, { ru: "С кем? Твори́тельный паде́ж", en: "With whom? The instrumental", ar: "مع من؟ حالة الأداة" },
    ["с + instrumental = with: с дру́гом, с сестро́й, ко́фе с молоко́м", "Endings: -ом / -ем (masculine, neuter), -ой / -ей (feminine)", "Pronouns: со мной, с тобо́й, с ним, с ней, с на́ми, с ва́ми, с ни́ми"],
    ["с", "вме́сте", "встреча́ться", "знако́миться", "разгова́ривать", "дружи́ть", "танцева́ть", "лимо́н", "варе́нье", "моро́женое", "бутербро́д", "пиро́г", "смета́на", "согла́сен"],
    "Who do you spend your free time with? Then order tea with lemon and jam and a sandwich.",
    ["instrumental", "food"]],
  [44, { ru: "Кем ты рабо́таешь?", en: "What do you do? The instrumental 2", ar: "ما عملك؟ حالة الأداة (٢)" },
    ["рабо́тать / быть / стать + instrumental: Я рабо́таю врачо́м. Я хочу́ стать учи́телем.", "занима́ться + instrumental: спо́ртом, му́зыкой, ру́сским языко́м", "интересова́ться and увлека́ться + instrumental"],
    ["стать", "интересова́ться", "увлека́ться", "хо́бби", "жи́вопись", "пла́вание", "программи́ст", "ме́неджер", "бухга́лтер", "юри́ст", "води́тель", "по́вар", "продаве́ц", "мечта́"],
    "A jobs-and-hobbies interview: what you do, what you are interested in and who you want to become.",
    ["instrumental", "professions"]],
  [45, { ru: "Како́й он челове́к?", en: "What is he like? Appearance and character", ar: "كيف هو؟ المظهر والشخصية" },
    ["Adjectives agree in the nominative, accusative and prepositional", "У неё дли́нные во́лосы и голубы́е глаза́.", "Он о́чень до́брый, но немно́го лени́вый."],
    ["высо́кий", "ни́зкий", "молодо́й", "у́мный", "до́брый", "весёлый", "серьёзный", "лени́вый", "во́лосы", "глаза́", "дли́нный", "коро́ткий", "похо́ж", "хара́ктер"],
    "Describe a friend or a famous person; the tutor asks questions and guesses who it is.",
    ["appearance", "adjectives"]],
  [46, { ru: "Бо́льше и лу́чше: сравне́ние", en: "Bigger and better: comparisons", ar: "أكبر وأفضل: المقارنة" },
    ["Comparatives in -ее: интере́снее, быстре́е, краси́вее", "Irregular: бо́льше, ме́ньше, лу́чше, ху́же, доро́же, деше́вле, ста́рше, моло́же", "…чем… and са́мый + adjective"],
    ["бо́льше", "ме́ньше", "лу́чше", "ху́же", "доро́же", "деше́вле", "ста́рше", "моло́же", "быстре́е", "ме́дленнее", "чем", "са́мый", "люби́мый", "предпочита́ть"],
    "Compare Cairo and Moscow, tea and coffee, trains and planes; say what your favourite things are.",
    ["comparatives", "adjectives"]],
  [47, { ru: "Пого́да и здоро́вье", en: "Weather and health", ar: "الطقس والصحة" },
    ["Weather: сего́дня хо́лодно / жа́рко, идёт дождь / снег, плюс / ми́нус пять гра́дусов", "У меня́ боли́т… (голова́, го́рло)", "Мне пло́хо; на́до / ну́жно + infinitive"],
    ["пого́да", "дождь", "снег", "со́лнце", "ве́тер", "гра́дус", "жа́рко", "зима́", "ле́то", "голова́", "го́рло", "боли́т", "температу́ра", "лека́рство"],
    "At the doctor's: explain what hurts and since when; then small talk about the weather.",
    ["weather", "health"]],
  [48, { ru: "Смо́трим: мультфи́льм", en: "Watch: a cartoon", ar: "نشاهد: رسوم متحركة" },
    ["Listening for descriptions of people, weather and feelings"],
    ["весна́", "о́сень", "о́блако", "дру́жба", "улы́бка", "смешно́й", "друзья́"],
    "Describe the characters' looks and personalities and retell the episode.",
    ["cartoon", "appearance", "weather"]],
  [49, { ru: "Повторе́ние: неде́ля 7", en: "Review: week 7", ar: "مراجعة: الأسبوع ٧" },
    ["Review: instrumental, adjectives, comparisons, weather and health"],
    [],
    "Speaking test: describe a friend, compare two cities, and explain a health problem to a doctor.",
    ["instrumental", "comparatives", "health"]],

  // ── Week 8 · Putting it together ─────────────────────────────────────────────
  [50, { ru: "Шесть падеже́й", en: "All six cases", ar: "الحالات الست" },
    ["The six cases and their questions: кто / что, кого́ / чего́, кому́ / чему́, кого́ / что, кем / чем, о ком / о чём", "One noun through all cases: кни́га, кни́ги, кни́ге, кни́гу, кни́гой, о кни́ге", "A map of prepositions and the cases they take"],
    ["паде́ж", "оконча́ние", "отве́т", "пра́вило", "приме́р", "оши́бка", "испра́вить", "запо́мнить", "повторя́ть", "упражне́ние", "зна́чит", "перево́д", "переводи́ть", "объясне́ние"],
    "Grammar clinic: the tutor says mixed sentences with a noun missing and you supply it in the right case.",
    ["cases-overview"]],
  [51, { ru: "Потому́ что и е́сли", en: "Because and if: complex sentences", ar: "لأن وإذا: الجمل المركبة" },
    ["потому́ что and поэ́тому", "е́сли…, (то)… and когда́…", "что and кото́рый: Я зна́ю, что… / Челове́к, кото́рый…"],
    ["потому́ что", "поэ́тому", "е́сли", "кото́рый", "хотя́", "что́бы", "тогда́", "наве́рное", "коне́чно", "наприме́р", "во-пе́рвых", "во-вторы́х", "кро́ме того́", "вообще́"],
    "Explain your reasons: why you are learning Russian, and what you will do if you visit Russia.",
    ["conjunctions"]],
  [52, { ru: "Дава́й встре́тимся!", en: "Let's meet! Calls and invitations", ar: "هيا نلتقي! المكالمات والدعوات" },
    ["Imperative: скажи́ / скажи́те, дай / да́йте, подожди́ / подожди́те, позвони́ / позвони́те", "Дава́й + perfective (let's): Дава́й встре́тимся в суббо́ту.", "On the phone: Алло́! Мо́жно А́нну? Вас пло́хо слы́шно."],
    ["дава́й", "встре́титься", "свобо́ден", "за́нят", "алло́", "подожда́ть", "перезвони́ть", "слы́шно", "приглаше́ние", "отказа́ться", "жаль", "Договори́лись!", "Дава́й на ты.", "в друго́й раз"],
    "Phone a friend (the tutor) to arrange a meeting; they are busy, so decline politely and agree on another time.",
    ["phone-calls", "invitations", "imperative"]],
  [53, { ru: "Путеше́ствие", en: "Travel", ar: "السفر" },
    ["At the hotel: У меня́ бронь на и́мя… / Во ско́лько за́втрак?", "At the airport: регистра́ция, поса́дка, вы́ход, рейс", "Problems: Я потеря́л(а)… / Помоги́те! / Где ближа́йший…?"],
    ["путеше́ствие", "аэропо́рт", "рейс", "регистра́ция", "поса́дка", "бага́ж", "чемода́н", "бронь", "но́мер", "потеря́ть", "Помоги́те!", "ближа́йший", "опозда́ть", "па́спортный контро́ль"],
    "Check in at a Moscow hotel, then report lost luggage at the airport.",
    ["travel", "transport"]],
  [54, { ru: "Расскажи́ исто́рию", en: "Tell a story", ar: "احكِ قصة" },
    ["Story order: снача́ла, пото́м, зате́м, вдруг, наконе́ц, в конце́ концо́в", "Aspect in stories: background imperfective (шёл дождь) and events perfective (я уви́дел)", "Reported speech: Он сказа́л, что…"],
    ["исто́рия", "одна́жды", "вдруг", "зате́м", "случи́ться", "уви́деть", "услы́шать", "поня́ть", "реши́ть", "испуга́ться", "смея́ться", "удиви́ться", "в конце́ концо́в", "ска́зка"],
    "Tell the tutor a short story about a trip or a funny day, then retell a story the tutor tells you.",
    ["storytelling", "aspect"]],
  [55, { ru: "Смо́трим: фильм и переска́з", en: "Watch: a film and retelling", ar: "نشاهد: فيلم وإعادة سرد" },
    ["Watching a longer piece and retelling it with the past tense and aspect"],
    ["геро́й", "сюже́т", "нача́ло", "коне́ц", "актёр", "режиссёр", "сериа́л"],
    "Retell the plot of what you watched and say what you liked and why.",
    ["listening", "storytelling", "culture"]],
  [56, { ru: "Фина́льный экза́мен", en: "Final exam", ar: "الاختبار النهائي" },
    ["Final review of the whole course: all cases, three tenses, aspect, motion verbs, complex sentences"],
    [],
    "Final interview (10 minutes): introduce yourself, describe your routine and family, tell a story and make plans with the examiner.",
    ["cases-overview", "storytelling", "travel"]],
];

export const SYLLABUS: SyllabusDay[] = rows.map(([n, title, grammar, words, scenario, topics]) => ({
  n,
  kind: kindOf(n),
  title,
  grammar,
  words,
  scenario,
  topics,
}));

export const WEEK_THEMES: Tri[] = [
  { ru: "Зву́ки и пе́рвые слова́", en: "Sounds and first words", ar: "الأصوات والكلمات الأولى" },
  { ru: "Я и мой мир", en: "Me and my world", ar: "أنا وعالمي" },
  { ru: "Где?", en: "Where?", ar: "أين؟" },
  { ru: "Хочу́ и мо́жно", en: "Wants and needs", ar: "الرغبات والطلبات" },
  { ru: "Мой день", en: "My day", ar: "يومي" },
  { ru: "Пое́хали!", en: "Going places", ar: "هيا ننطلق!" },
  { ru: "Лю́ди и вку́сы", en: "People and preferences", ar: "الناس والأذواق" },
  { ru: "Всё вме́сте", en: "Putting it together", ar: "كل شيء معًا" },
];
