// Controlled vocabulary of topic tags. Lessons tag themselves with these; the media library
// indexes verified videos by them. Adding a tag here means the media library must cover it.

export const TOPICS = [
  "alphabet",
  "handwriting",
  "pronunciation",
  "stress",
  "greetings",
  "introductions",
  "numbers",
  "questions",
  "gender",
  "possessives",
  "plurals",
  "present-tense",
  "languages",
  "family",
  "professions",
  "prepositional",
  "city",
  "directions",
  "time",
  "days-week",
  "shopping",
  "accusative",
  "food",
  "cafe",
  "adjectives",
  "colors",
  "past-tense",
  "daily-routine",
  "reflexive-verbs",
  "genitive",
  "aspect",
  "dative",
  "future-tense",
  "motion-verbs",
  "transport",
  "imperative",
  "instrumental",
  "appearance",
  "comparatives",
  "weather",
  "health",
  "phone-calls",
  "invitations",
  "travel",
  "storytelling",
  "conjunctions",
  "cases-overview",
  "cartoon",
  "songs",
  "listening",
  "culture",
] as const;

export type Topic = (typeof TOPICS)[number];

export const TOPIC_SET: ReadonlySet<string> = new Set<string>(TOPICS);
